name: WorldsX
version: 1.3.0
api: 5.0.0
main: blackjack200\worldsx\WorldsX
author: Blackjack200
website: https://github.com/Blackjack200/WorldsX.git
permissions:
  worldsx.command:
    description: "Allows the user to use the /worldsx command."
    default: op
  worldsx.gamerule:
    description: "Allows the user to use the /gamerule command."
    default: op
